<?php
return [
    'Tx_Oelib_Interface_Address' => \OliverKlee\Oelib\Interfaces\Address::class,
    'Tx_Oelib_Interface_ConfigurationCheckable' => \OliverKlee\Oelib\Interfaces\ConfigurationCheckable::class,
    'Tx_Oelib_Interface_GeocodingLookup' => \OliverKlee\Oelib\Interfaces\GeocodingLookup::class,
    'Tx_Oelib_Interface_Geo' => \OliverKlee\Oelib\Interfaces\Geo::class,
    'Tx_Oelib_Interface_Identity' => \OliverKlee\Oelib\Interfaces\Identity::class,
    'Tx_Oelib_Interface_LoginManager' => \OliverKlee\Oelib\Interfaces\LoginManager::class,
    'Tx_Oelib_Interface_MailRole' => \OliverKlee\Oelib\Interfaces\MailRole::class,
    'Tx_Oelib_Interface_MapPoint' => \OliverKlee\Oelib\Interfaces\MapPoint::class,
    'Tx_Oelib_Interface_Sortable' => \OliverKlee\Oelib\Interfaces\Sortable::class,
    'Tx_Oelib_Exception_AccessDenied' => \OliverKlee\Oelib\Exception\AccessDeniedException::class,
    'Tx_Oelib_Exception_Database' => \OliverKlee\Oelib\Exception\DatabaseException::class,
    'Tx_Oelib_Exception_EmptyQueryResult' => \OliverKlee\Oelib\Exception\EmptyQueryResultException::class,
    'Tx_Oelib_Exception_NotFound' => \OliverKlee\Oelib\Exception\NotFoundException::class,
    'Tx_Oelib_FrontEnd_UserWithoutCookies' => \OliverKlee\Oelib\Frontend\UserWithoutCookies::class,
    'Tx_Oelib_Geocoding_Calculcator' => \OliverKlee\Oelib\Geocoding\GeoCalculcator::class,
    'Tx_Oelib_Geocoding_Dummy' => \OliverKlee\Oelib\Geocoding\DummyGeocodingLookup::class,
    'Tx_Oelib_Geocoding_Google' => \OliverKlee\Oelib\Geocoding\GoogleGeocoding::class,
];
